name: sudo_aprender_brincar
description: A new Flutter project for SUDO Aprender & Brincar.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Main image folder
    # Individual image listing if preferred:
    # - assets/images/toothbrush.png
    # - assets/images/toothpaste.png
    # - assets/images/teeth_normal.png
    # - assets/images/teeth_brushed.png
    # - assets/images/cup.png
    # - assets/images/avatar_happy.png
